### ISSUE TITLE
"Add to edit" functionality overwritten

### ISSUE THREAD

**Issue by seanbjornsson** [tjx666/vscode-classic-experience#8]
First off, I love the work y'all are doing here. I needed my keybindings back!

I wanted to point out however that [in the README](https://github.com/tjx666/vscode-classic-experience/blob/516043e636bf5c538b7f4643654a651c2a0cdea2/README.md?plain=1#L25) it is indicated that `⇧ + ⌘ + K` now deletes lines but was previously equivalent to what is now `⌘ + E` (Open Edit). This is not true (See Cursor documentation [here](https://docs.cursor.com/context/%40-symbols/%40-code#from-the-editor)), this used to be "Add to Edit". 

I think this is an ok tradeoff, as I suspect many people coming to this extension use  `⇧ + ⌘ + K` for delete line and would prefer that tradeoff. However, I thought it would be better to either 1) just be clear in the readme that that functionality is lost or 2) retain that functionality. 

If this functionality is retained, and I just am unaware (Cmd + shift + E does not do "Add to Edit"), please let me know! And then maybe we can update the readme accordingly.

**Comment by tjx666** [comment]
@seanbjornsson The readme is wrong, should be corrected to `cmd + shift + ]`

**Comment by tjx666** [comment]
After I did some investigation, if I understand right:

cmd + k: open inline edit
cmd + shift + k: add selection to composer bar(Cursor say it is Add to Edit).

The key question is `Cmd + Shift + E` is a built-in shortcut to focus to File Explorer.

We know, `Cmd + I` can open composer, so another idea is to user `Cmd + Shift + I` to do `add selection to composer bar`. But `Cmd + Shift + I` had been bind to `Open Control Panel`.

<img width="602" alt="image" src="https://github.com/user-attachments/assets/d55bf862-df08-40e1-ab38-95376874ecc5">

Hard to decide which shortcut `Cmd + Shift + K` should changed to.

**Comment by tjx666** [comment]
I had add some note to readme

**Comment by seanbjornsson** [comment]
Agreed, there isn't a clear replacement given what you outlined above. I think a note in the readme is good for now!

**Comment by seanbjornsson** [comment]
Agreed, there isn't a clear replacement given what you outlined above. I think a note in the readme is good for now!
